# Set the version of docker compose to use
version: '3.9'

# The containers that compose the project
services:
  tests:
    image: postgres:13
    restart: always
    container_name: tests
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
      POSTGRES_DB: tests
    hostname: tests
    volumes:
      - postgres-data-tests:/var/lib/postgresql/data

  prisma-postgres-tests-api:
    stdin_open: true
    build:
      context: .
      dockerfile: tests/Dockerfile
    container_name: prisma-postgres-tests-api
    environment:
      DATABASE_URL: postgresql://prisma:prisma@tests:5432/tests?schema=public
    env_file:
      - ./.env.test
    depends_on:
      - tests
    ports:
      - "8082:8081"
    restart: always

volumes:
  postgres-data-tests: