# version: "3.9"
# services:
#   postgres:
#     image: postgres:latest
#     container_name: postgres
#     hostname: postgres
#     ports:
#       - 5432:5432
#     environment:
#       POSTGRES_USER: postgres
#       POSTGRES_PASSWORD: admin
#       POSTGRES_DB: jira_db
#     volumes:
#       - postgres-data:/var/lib/postgresql/data
#     restart: unless-stopped

#   prisma-postgres-api:
#     stdin_open: true
#     build:
#       context: .
#       dockerfile: Dockerfile
#     container_name: prisma-postgres-api
#     depends_on:
#       - postgres
#     ports:
#       - "8081:8081"
#     restart: always

# volumes:
#   postgres-data:
