const TASK_PRIORITY = ["HIGHEST", "MEDIUM", "LOWEST"];
const BOARD_COLUMNS = [
  "TO_DO",
  "IN_PROGRESS",
  "READY_FOR_TESTING",
  "TESTING",
  "DONE",
];

module.exports = { TASK_PRIORITY, BOARD_COLUMNS };
